Internal server error while processing request '/sub?target=clash&url=https%3A%2F%2Fchromego-sub.netlify.app%2Fsub%2Fmerged_proxies_new.yaml&add_emoji=true&remove_emoji=false&append_type=true&tfo=false&udp=true&list=true&sort=false&script=false&insert=true&scv=true&fdn=true&expand=false&append_info=true&prepend=true&classic=false&tls13=false&new_name=false'!

  exception: YAML::TypedBadConversion<bool>
  what(): yaml-cpp: error at line 1319, column 10: bad conversion