proxies:
  - {name: BESTIIVPNBOT تست و خرید, server: 62.60.192.209, port: 80, type: vless, tls: true, packet-encoding: xudp, uuid: f5f2458c-5fcb-4820-82c2-2997492c54d5, skip-cert-verify: false, udp: true, tfo: false}