proxies:
  - {name: "[SS] `@mtproto_proserver", server: 163.171.137.76, port: 47394, type: ss, cipher: chacha20-ietf-poly1305, password: eafad96826c79ddd, tfo: false}
  - {name: "[SS] Telegram:  @Zero_Tunnel", server: 102.37.156.224, port: 443, type: ss, cipher: chacha20-ietf-poly1305, password: aduB9HGxQHjA2SBMRjkHX6, tfo: false}